export { default as UTabs } from './Tabs'
export { default as UTab } from './Tab'
export type { UTabsPropsType } from './Tabs'
export { default as UTabPane } from './TabPane'
export type { UTabPanePropsType } from './TabPane'
